# Generated by Django 4.2.4 on 2024-04-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="udetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.CharField(max_length=10)),
                ("gender", models.CharField(max_length=10)),
                ("height", models.CharField(max_length=10)),
                ("weight", models.CharField(max_length=10)),
                ("systolic", models.CharField(max_length=10)),
                ("diastolic", models.CharField(max_length=10)),
                ("cholestrol", models.CharField(max_length=10)),
                ("glucose", models.CharField(max_length=10)),
                ("smoking", models.CharField(max_length=10)),
                ("alchohol", models.CharField(max_length=10)),
                ("active", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("pnum", models.CharField(max_length=10)),
                ("email", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
            ],
        ),
    ]
